language: objective-c
osx_image: xcode7.3
script:
  - xctool -project TravisDemo.xcodeproj -scheme TravisDemo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project TravisDemo.xcodeproj -scheme TravisDemoTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
